# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Mon Mar 25 16:22:47 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(418, 603)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.consoleLabel = QtGui.QLabel(self.centralwidget)
        self.consoleLabel.setTextFormat(QtCore.Qt.RichText)
        self.consoleLabel.setObjectName("consoleLabel")
        self.horizontalLayout_5.addWidget(self.consoleLabel)
        spacerItem = QtGui.QSpacerItem(17, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.enableConsoleInput = QtGui.QCheckBox(self.centralwidget)
        self.enableConsoleInput.setObjectName("enableConsoleInput")
        self.horizontalLayout_5.addWidget(self.enableConsoleInput)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.console = QtGui.QPlainTextEdit(self.centralwidget)
        self.console.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.console.setReadOnly(True)
        self.console.setMaximumBlockCount(1000)
        self.console.setObjectName("console")
        self.verticalLayout.addWidget(self.console)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.inputLabel = QtGui.QLabel(self.centralwidget)
        self.inputLabel.setTextFormat(QtCore.Qt.RichText)
        self.inputLabel.setObjectName("inputLabel")
        self.horizontalLayout_3.addWidget(self.inputLabel)
        spacerItem1 = QtGui.QSpacerItem(17, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.liveRadio = QtGui.QRadioButton(self.centralwidget)
        self.liveRadio.setChecked(True)
        self.liveRadio.setObjectName("liveRadio")
        self.liveOrPlaybackButtonGroup = QtGui.QButtonGroup(MainWindow)
        self.liveOrPlaybackButtonGroup.setObjectName("liveOrPlaybackButtonGroup")
        self.liveOrPlaybackButtonGroup.addButton(self.liveRadio)
        self.horizontalLayout_3.addWidget(self.liveRadio)
        self.playbackRadio = QtGui.QRadioButton(self.centralwidget)
        self.playbackRadio.setObjectName("playbackRadio")
        self.liveOrPlaybackButtonGroup.addButton(self.playbackRadio)
        self.horizontalLayout_3.addWidget(self.playbackRadio)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.liveOrPlaybackPages = QtGui.QStackedWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.liveOrPlaybackPages.sizePolicy().hasHeightForWidth())
        self.liveOrPlaybackPages.setSizePolicy(sizePolicy)
        self.liveOrPlaybackPages.setObjectName("liveOrPlaybackPages")
        self.livePage = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.livePage.sizePolicy().hasHeightForWidth())
        self.livePage.setSizePolicy(sizePolicy)
        self.livePage.setObjectName("livePage")
        self.gridLayout_2 = QtGui.QGridLayout(self.livePage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listeningPortLabel = QtGui.QLabel(self.livePage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listeningPortLabel.sizePolicy().hasHeightForWidth())
        self.listeningPortLabel.setSizePolicy(sizePolicy)
        self.listeningPortLabel.setObjectName("listeningPortLabel")
        self.gridLayout_2.addWidget(self.listeningPortLabel, 0, 1, 1, 1)
        self.listeningPortInput = QtGui.QSpinBox(self.livePage)
        self.listeningPortInput.setMinimumSize(QtCore.QSize(100, 0))
        self.listeningPortInput.setKeyboardTracking(False)
        self.listeningPortInput.setMaximum(65535)
        self.listeningPortInput.setObjectName("listeningPortInput")
        self.gridLayout_2.addWidget(self.listeningPortInput, 0, 2, 1, 1)
        self.liveOrPlaybackPages.addWidget(self.livePage)
        self.playbackPage = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playbackPage.sizePolicy().hasHeightForWidth())
        self.playbackPage.setSizePolicy(sizePolicy)
        self.playbackPage.setObjectName("playbackPage")
        self.gridLayout = QtGui.QGridLayout(self.playbackPage)
        self.gridLayout.setObjectName("gridLayout")
        self.startTimeLabel = QtGui.QLabel(self.playbackPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startTimeLabel.sizePolicy().hasHeightForWidth())
        self.startTimeLabel.setSizePolicy(sizePolicy)
        self.startTimeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.startTimeLabel.setObjectName("startTimeLabel")
        self.gridLayout.addWidget(self.startTimeLabel, 5, 0, 1, 1)
        self.endTimeInput = QtGui.QTimeEdit(self.playbackPage)
        self.endTimeInput.setCurrentSection(QtGui.QDateTimeEdit.HourSection)
        self.endTimeInput.setObjectName("endTimeInput")
        self.gridLayout.addWidget(self.endTimeInput, 6, 1, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(45, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 5, 5, 1, 1)
        self.endTimeLabel = QtGui.QLabel(self.playbackPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endTimeLabel.sizePolicy().hasHeightForWidth())
        self.endTimeLabel.setSizePolicy(sizePolicy)
        self.endTimeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.endTimeLabel.setObjectName("endTimeLabel")
        self.gridLayout.addWidget(self.endTimeLabel, 6, 0, 1, 1)
        self.startTimeResetButton = QtGui.QPushButton(self.playbackPage)
        self.startTimeResetButton.setObjectName("startTimeResetButton")
        self.gridLayout.addWidget(self.startTimeResetButton, 5, 3, 1, 2)
        self.endTimeResetButton = QtGui.QPushButton(self.playbackPage)
        self.endTimeResetButton.setObjectName("endTimeResetButton")
        self.gridLayout.addWidget(self.endTimeResetButton, 6, 3, 1, 2)
        spacerItem3 = QtGui.QSpacerItem(45, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 6, 5, 1, 1)
        self.startTimeInput = QtGui.QTimeEdit(self.playbackPage)
        self.startTimeInput.setObjectName("startTimeInput")
        self.gridLayout.addWidget(self.startTimeInput, 5, 1, 1, 2)
        self.playbackTimeLabel = QtGui.QLabel(self.playbackPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playbackTimeLabel.sizePolicy().hasHeightForWidth())
        self.playbackTimeLabel.setSizePolicy(sizePolicy)
        self.playbackTimeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.playbackTimeLabel.setObjectName("playbackTimeLabel")
        self.gridLayout.addWidget(self.playbackTimeLabel, 3, 0, 1, 1)
        self.playbackTimeInput = QtGui.QTimeEdit(self.playbackPage)
        self.playbackTimeInput.setCurrentSection(QtGui.QDateTimeEdit.HourSection)
        self.playbackTimeInput.setObjectName("playbackTimeInput")
        self.gridLayout.addWidget(self.playbackTimeInput, 3, 1, 1, 2)
        self.widget = QtGui.QWidget(self.playbackPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.playOrPauseButton = QtGui.QPushButton(self.widget)
        self.playOrPauseButton.setObjectName("playOrPauseButton")
        self.horizontalLayout.addWidget(self.playOrPauseButton)
        self.stopButton = QtGui.QPushButton(self.widget)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout.addWidget(self.stopButton)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.gridLayout.addWidget(self.widget, 1, 0, 1, 6)
        self.playbackFileLabel = QtGui.QLabel(self.playbackPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playbackFileLabel.sizePolicy().hasHeightForWidth())
        self.playbackFileLabel.setSizePolicy(sizePolicy)
        self.playbackFileLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.playbackFileLabel.setObjectName("playbackFileLabel")
        self.gridLayout.addWidget(self.playbackFileLabel, 0, 0, 1, 1)
        self.widget1 = QtGui.QWidget(self.playbackPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget1.sizePolicy().hasHeightForWidth())
        self.widget1.setSizePolicy(sizePolicy)
        self.widget1.setAcceptDrops(True)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.playbackFileInput = QtGui.QLineEdit(self.widget1)
        self.playbackFileInput.setObjectName("playbackFileInput")
        self.horizontalLayout_2.addWidget(self.playbackFileInput)
        self.playbackFileOpenButton = QtGui.QToolButton(self.widget1)
        self.playbackFileOpenButton.setObjectName("playbackFileOpenButton")
        self.horizontalLayout_2.addWidget(self.playbackFileOpenButton)
        self.gridLayout.addWidget(self.widget1, 0, 1, 1, 5)
        self.loopPlaybackInput = QtGui.QCheckBox(self.playbackPage)
        self.loopPlaybackInput.setObjectName("loopPlaybackInput")
        self.gridLayout.addWidget(self.loopPlaybackInput, 3, 3, 1, 3)
        self.liveOrPlaybackPages.addWidget(self.playbackPage)
        self.verticalLayout.addWidget(self.liveOrPlaybackPages)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.outputLabel = QtGui.QLabel(self.centralwidget)
        self.outputLabel.setTextFormat(QtCore.Qt.RichText)
        self.outputLabel.setObjectName("outputLabel")
        self.horizontalLayout_4.addWidget(self.outputLabel)
        spacerItem6 = QtGui.QSpacerItem(17, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.enableOutputInput = QtGui.QCheckBox(self.centralwidget)
        self.enableOutputInput.setObjectName("enableOutputInput")
        self.horizontalLayout_4.addWidget(self.enableOutputInput)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.outputDestinationHBox = QtGui.QHBoxLayout()
        self.outputDestinationHBox.setObjectName("outputDestinationHBox")
        self.outputAddressLabel = QtGui.QLabel(self.centralwidget)
        self.outputAddressLabel.setObjectName("outputAddressLabel")
        self.outputDestinationHBox.addWidget(self.outputAddressLabel)
        self.outputAddressInput = QtGui.QLineEdit(self.centralwidget)
        self.outputAddressInput.setMinimumSize(QtCore.QSize(75, 0))
        self.outputAddressInput.setObjectName("outputAddressInput")
        self.outputDestinationHBox.addWidget(self.outputAddressInput)
        self.outputPortLabel = QtGui.QLabel(self.centralwidget)
        self.outputPortLabel.setObjectName("outputPortLabel")
        self.outputDestinationHBox.addWidget(self.outputPortLabel)
        self.outputPortInput = QtGui.QSpinBox(self.centralwidget)
        self.outputPortInput.setKeyboardTracking(False)
        self.outputPortInput.setMaximum(65535)
        self.outputPortInput.setProperty("value", 37001)
        self.outputPortInput.setObjectName("outputPortInput")
        self.outputDestinationHBox.addWidget(self.outputPortInput)
        self.verticalLayout.addLayout(self.outputDestinationHBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 418, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSaveAs = QtGui.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.startTimeLabel.setBuddy(self.startTimeInput)
        self.endTimeLabel.setBuddy(self.endTimeInput)
        self.playbackTimeLabel.setBuddy(self.playbackTimeInput)
        self.playbackFileLabel.setBuddy(self.playbackFileInput)
        self.outputAddressLabel.setBuddy(self.outputAddressInput)
        self.outputPortLabel.setBuddy(self.outputPortInput)

        self.retranslateUi(MainWindow)
        self.liveOrPlaybackPages.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "OSC Console", None, QtGui.QApplication.UnicodeUTF8))
        self.consoleLabel.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Console</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.enableConsoleInput.setText(QtGui.QApplication.translate("MainWindow", "Enable", None, QtGui.QApplication.UnicodeUTF8))
        self.inputLabel.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Input</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.liveRadio.setText(QtGui.QApplication.translate("MainWindow", "Live", None, QtGui.QApplication.UnicodeUTF8))
        self.playbackRadio.setText(QtGui.QApplication.translate("MainWindow", "Playback", None, QtGui.QApplication.UnicodeUTF8))
        self.listeningPortLabel.setText(QtGui.QApplication.translate("MainWindow", "Listening port", None, QtGui.QApplication.UnicodeUTF8))
        self.startTimeLabel.setText(QtGui.QApplication.translate("MainWindow", "Start time", None, QtGui.QApplication.UnicodeUTF8))
        self.endTimeInput.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "HH:mm:ss", None, QtGui.QApplication.UnicodeUTF8))
        self.endTimeLabel.setText(QtGui.QApplication.translate("MainWindow", "End time", None, QtGui.QApplication.UnicodeUTF8))
        self.startTimeResetButton.setText(QtGui.QApplication.translate("MainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.endTimeResetButton.setText(QtGui.QApplication.translate("MainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.startTimeInput.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "HH:mm:ss", None, QtGui.QApplication.UnicodeUTF8))
        self.playbackTimeLabel.setText(QtGui.QApplication.translate("MainWindow", "Playback time", None, QtGui.QApplication.UnicodeUTF8))
        self.playbackTimeInput.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "HH:mm:ss", None, QtGui.QApplication.UnicodeUTF8))
        self.playOrPauseButton.setText(QtGui.QApplication.translate("MainWindow", "&Play", None, QtGui.QApplication.UnicodeUTF8))
        self.playOrPauseButton.setShortcut(QtGui.QApplication.translate("MainWindow", "Space, P", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setText(QtGui.QApplication.translate("MainWindow", "&Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setShortcut(QtGui.QApplication.translate("MainWindow", "S", None, QtGui.QApplication.UnicodeUTF8))
        self.playbackFileLabel.setText(QtGui.QApplication.translate("MainWindow", "Playback file", None, QtGui.QApplication.UnicodeUTF8))
        self.playbackFileOpenButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.loopPlaybackInput.setText(QtGui.QApplication.translate("MainWindow", "Loop playback", None, QtGui.QApplication.UnicodeUTF8))
        self.outputLabel.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Output</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.enableOutputInput.setText(QtGui.QApplication.translate("MainWindow", "Enable", None, QtGui.QApplication.UnicodeUTF8))
        self.outputAddressLabel.setText(QtGui.QApplication.translate("MainWindow", "Address", None, QtGui.QApplication.UnicodeUTF8))
        self.outputAddressInput.setText(QtGui.QApplication.translate("MainWindow", "127.0.0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.outputPortLabel.setText(QtGui.QApplication.translate("MainWindow", "Port", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAs.setText(QtGui.QApplication.translate("MainWindow", "Save log as", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAs.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))

